// react/demo/src/daisyui/samples/carousel/Carousel.tsx
import {type CarouselProps, createCarousel} from '@agnos-ui/react-headless/components/carousel';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import classNames from 'classnames';
import AutoPlay from 'embla-carousel-autoplay';
import {useMemo, type ReactNode} from 'react';
import PreviousSvg from '@agnos-ui/common/samples/carousel/previous.svg?react';
import NextSvg from '@agnos-ui/common/samples/carousel/next.svg?react';

export function Carousel<Item>(
	props: Partial<Omit<CarouselProps, 'plugins'>> & {
		items: Item[];
		withNavArrows?: boolean;
		withNavIndicators?: boolean;
		autoplay?: boolean;
		slide: (props: {item: Item}) => ReactNode;
	},
) {
	const plugins = useMemo(
		() => (props.autoplay ? [AutoPlay({playOnInit: true, stopOnInteraction: false, stopOnMouseEnter: true, stopOnFocusIn: true})] : []),
		[props.autoplay],
	);
	const {
		state,
		directives: {carouselDirective},
		api: {scrollPrev, scrollNext, scrollTo},
	} = useWidgetWithConfig(createCarousel, {...props, plugins, container: '.container'}, 'carousel');
	const Slide = props.slide;
	return (
		<div className="overflow-hidden relative cursor-grab active:cursor-grabbing flex flex-col-reverse" {...useDirective(carouselDirective)}>
			{props.withNavIndicators && (
				<div className="flex w-full justify-center gap-2 py-2 cursor-auto">
					{props.items.map((_, index) => (
						<button
							className={classNames('btn', 'btn-xs', 'md:btn-sm', {'btn-active': state.selectedScrollSnap === index})}
							onClick={() => scrollTo(index)}
							aria-label={`Go to slide ${index + 1}`}
							key={index}
						>
							{index + 1}
						</button>
					))}
				</div>
			)}
			<div className="flex container">
				{props.items.map((item, index) => (
					<div className="basis-full min-w-0 shrink-0 grow-0 flex justify-center" key={index}>
						<Slide item={item} />
					</div>
				))}
			</div>
			{props.withNavArrows && (
				<div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
					<button
						className="btn btn-sm md:btn-md btn-circle opacity-75 hover:opacity-100"
						onPointerDown={(e) => e.preventDefault()}
						disabled={!state.canScrollPrev}
						onClick={scrollPrev}
						aria-label="Go to previous slide"
					>
						<PreviousSvg />
					</button>
					<button
						className="btn btn-sm md:btn-md btn-circle opacity-75 hover:opacity-100"
						onPointerDown={(e) => e.preventDefault()}
						disabled={!state.canScrollNext}
						onClick={scrollNext}
						aria-label="Go to next slide"
					>
						<NextSvg />
					</button>
				</div>
			)}
		</div>
	);
}

// angular/demo/daisyui/src/app/samples/carousel/carousel.component.ts
import {
	auBooleanAttribute,
	BaseWidgetDirective,
	callWidgetFactory,
	createCarousel,
	UseDirective,
	type CarouselWidget,
} from '@agnos-ui/angular-headless';
import {Component, effect, inject, input, ChangeDetectionStrategy, linkedSignal, Directive, contentChild, TemplateRef} from '@angular/core';
import AutoPlay from 'embla-carousel-autoplay';
import previousSvg from '@agnos-ui/common/samples/carousel/previous.svg';
import nextSvg from '@agnos-ui/common/samples/carousel/next.svg';
import pauseSvg from '@agnos-ui/common/samples/carousel/pause.svg';
import playSvg from '@agnos-ui/common/samples/carousel/play.svg';
import {DomSanitizer} from '@angular/platform-browser';
import {NgTemplateOutlet} from '@angular/common';

interface Photo {
	src: string;
	alt: string;
	id: string;
}

@Directive({selector: 'ng-template[appCarouselSlide]'})
export class CarouselSlideDirective {
	readonly templateRef = inject(TemplateRef);
	static ngTemplateContextGuard(_dir: CarouselSlideDirective, context: unknown): context is Photo {
		return true;
	}
}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'app-carousel',
	templateUrl: 'carousel.component.html',
	imports: [UseDirective, NgTemplateOutlet],
})
export class CarouselComponent extends BaseWidgetDirective<CarouselWidget> {
	readonly photos = input.required<Photo[]>();
	readonly dragFree = input(false, {transform: auBooleanAttribute});
	readonly loop = input(true, {transform: auBooleanAttribute});
	readonly autoplay = input(true, {transform: auBooleanAttribute});
	readonly showNavigationIndicators = input(true, {transform: auBooleanAttribute});
	readonly showNavigationArrows = input(true, {transform: auBooleanAttribute});
	readonly direction = input<'rtl' | 'ltr'>('ltr');

	readonly slideTemplate = contentChild.required(CarouselSlideDirective);

	private readonly sanitizer = inject(DomSanitizer);
	readonly previousSvg = this.sanitizer.bypassSecurityTrustHtml(previousSvg);
	readonly nextSvg = this.sanitizer.bypassSecurityTrustHtml(nextSvg);
	readonly pauseSvg = this.sanitizer.bypassSecurityTrustHtml(pauseSvg);
	readonly playSvg = this.sanitizer.bypassSecurityTrustHtml(playSvg);

	readonly playing = linkedSignal(() => this.autoplay());

	constructor() {
		const widget = callWidgetFactory(createCarousel, {
			widgetName: 'carousel',
			defaultConfig: {
				container: '.container',
			},
		});
		super(widget);
		effect(() => {
			widget.patch({
				plugins: this.autoplay() ? [AutoPlay({playOnInit: true, stopOnFocusIn: true, delay: 2_000})] : [],
			});
		});
	}

	togglePlay() {
		if (!this.playing()) {
			this.api.plugins()!.autoplay.play();
		} else {
			this.api.plugins()!.autoplay.stop();
		}
		this.playing.update((val) => !val);
	}
}

<div class="overflow-hidden relative cursor-grab active:cursor-grabbing flex flex-col-reverse" [auUse]="directives.carouselDirective">
	@if (withNavIndicators()) {
		<div class="flex w-full justify-center gap-2 py-2 cursor-auto">
			@for (item of items(); track item; let index = $index) {
				<button
					class="btn btn-xs md:btn-sm"
					[class.btn-active]="state.selectedScrollSnap() === index"
					(click)="api.scrollTo(index)"
					attr.aria-label="Go to slide {{ index + 1 }}"
				>
					{{ index + 1 }}
				</button>
			}
		</div>
	}
	<div class="flex container">
		@for (item of items(); track item) {
			<div class="basis-full min-w-0 shrink-0 grow-0 flex justify-center">
				<ng-container *ngTemplateOutlet="slideRef().templateRef; context: {$implicit: item}" />
			</div>
		}
	</div>
	@if (withNavArrows()) {
		<div class="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
			<button
				class="btn btn-sm md:btn-md btn-circle opacity-75 hover:opacity-100"
				(pointerdown)="$event.preventDefault()"
				[disabled]="!state.canScrollPrev()"
				(click)="api.scrollPrev()"
				aria-label="Go to previous slide"
				[innerHTML]="previousSvg"
			></button>
			<button
				class="btn btn-sm md:btn-md btn-circle opacity-75 hover:opacity-100"
				(pointerdown)="$event.preventDefault()"
				[disabled]="!state.canScrollNext()"
				(click)="api.scrollNext()"
				aria-label="Go to next slide"
				[innerHTML]="nextSvg"
			></button>
		</div>
	}
</div>
