// svelte/demo/src/daisyui/samples/progressbar/Progressbar.svelte
<script lang="ts">
	import {createProgressbar, type ProgressbarProps} from '@agnos-ui/svelte-headless/components/progressbar';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	let {className, ...props}: Partial<Omit<ProgressbarProps, 'min'>> & {className?: string} = $props();

	const {
		state,
		directives: {ariaDirective},
	} = callWidgetFactory({
		factory: createProgressbar,
		widgetName: 'progressbar',
		get props() {
			return {...props};
		},
		enablePatchChanged: true,
	});
</script>

<progress use:ariaDirective class="progress {className}" value={state.value} max={state.max}></progress>

// react/demo/src/daisyui/samples/progressbar/Progressbar.tsx
import {type ProgressbarProps, createProgressbar} from '@agnos-ui/react-headless/components/progressbar';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import classNames from 'classnames';

export function Progressbar({className, ...props}: Partial<Omit<ProgressbarProps, 'min'>> & {className?: string}) {
	const {state, directives} = useWidgetWithConfig(createProgressbar, props, 'progressbar');
	return <progress className={classNames('progress', className)} value={state.value} max={state.max} {...useDirective(directives.ariaDirective)} />;
}
