// react/demo/src/daisyui/samples/progressbar/RadialProgress.tsx
import {type ProgressbarProps, createProgressbar} from '@agnos-ui/react-headless/components/progressbar';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import classNames from 'classnames';
import {useMemo, type CSSProperties} from 'react';

export function RadialProgress({className, ...props}: Partial<ProgressbarProps> & {className?: string}) {
	const {state, directives} = useWidgetWithConfig(createProgressbar, props, 'progressbar');

	const percentFormat = useMemo(
		() =>
			new Intl.NumberFormat('default', {
				style: 'percent',
				minimumFractionDigits: 0,
				maximumFractionDigits: 1,
			}),
		[],
	);
	const style = {
		['--thickness']: '0.4rem',
		['--value']: state.percentage,
	} as CSSProperties;
	return (
		<div className={classNames('radial-progress', className)} style={style} {...useDirective(directives.ariaDirective)}>
			{percentFormat.format(state.percentage / 100)}
		</div>
	);
}

// svelte/demo/src/daisyui/samples/progressbar/RadialProgress.svelte
<script lang="ts">
	import {createProgressbar, type ProgressbarProps} from '@agnos-ui/svelte-headless/components/progressbar';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	let {className, ...props}: Partial<ProgressbarProps> & {className: string} = $props();

	const {
		state,
		directives: {ariaDirective},
	} = callWidgetFactory({
		factory: createProgressbar,
		widgetName: 'progressbar',
		get props() {
			return {...props};
		},
		enablePatchChanged: true,
	});

	const percentFormat = new Intl.NumberFormat('default', {
		style: 'percent',
		minimumFractionDigits: 0,
		maximumFractionDigits: 1,
	});
</script>

<div use:ariaDirective class="radial-progress {className}" style="--thickness: 0.4rem; --value:{state.percentage};">
	{percentFormat.format(state.percentage / 100)}
</div>
