// angular/demo/daisyui/src/app/samples/progressbar/radial-progress.component.ts
import {
	BaseWidgetDirective,
	auNumberAttribute,
	callWidgetFactory,
	type ProgressbarWidget,
	createProgressbar,
	UseDirective,
} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, input} from '@angular/core';

@Component({
	selector: 'app-radial-progress',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [UseDirective],
	template: ` <div
		class="radial-progress"
		[class]="className()"
		[style.--thickness]="'0.4rem'"
		[style.--value]="state.percentage()"
		[auUse]="directives.ariaDirective"
	>
		{{ percentFormat.format(state.percentage() / 100) }}
	</div>`,
})
export class RadialProgressComponent extends BaseWidgetDirective<ProgressbarWidget> {
	readonly min = input(undefined, {transform: auNumberAttribute});
	readonly max = input(undefined, {transform: auNumberAttribute});
	readonly value = input(undefined, {transform: auNumberAttribute});
	readonly ariaLabel = input<string>();
	readonly className = input<string>();
	readonly ariaValueTextFn = input<(value: number, minimum: number, maximum: number) => string | undefined>();

	constructor() {
		super(
			callWidgetFactory({
				factory: createProgressbar,
				widgetName: 'progressbar',
			}),
		);
	}
	readonly percentFormat = new Intl.NumberFormat('default', {
		style: 'percent',
		minimumFractionDigits: 0,
		maximumFractionDigits: 1,
	});
}

// svelte/demo/src/daisyui/samples/progressbar/RadialProgress.svelte
<script lang="ts">
	import {createProgressbar, type ProgressbarProps} from '@agnos-ui/svelte-headless/components/progressbar';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	let {className, ...props}: Partial<ProgressbarProps> & {className: string} = $props();

	const {
		state,
		directives: {ariaDirective},
	} = callWidgetFactory({
		factory: createProgressbar,
		widgetName: 'progressbar',
		get props() {
			return {...props};
		},
		enablePatchChanged: true,
	});

	const percentFormat = new Intl.NumberFormat('default', {
		style: 'percent',
		minimumFractionDigits: 0,
		maximumFractionDigits: 1,
	});
</script>

<div use:ariaDirective class="radial-progress {className}" style="--thickness: 0.4rem; --value:{state.percentage};">
	{percentFormat.format(state.percentage / 100)}
</div>
