// react/bootstrap/src/components/toast/toast.tsx
import {useWidgetWithConfig} from '../../config';
import {Slot} from '@agnos-ui/react-headless/slot';
import {useDirective, useDirectives} from '@agnos-ui/react-headless/utils/directive';
import type {ForwardRefExoticComponent, PropsWithChildren, RefAttributes} from 'react';
import {forwardRef, useImperativeHandle} from 'react';
import type {AdaptSlotContentProps, AdaptWidgetSlots, WidgetFactory, WidgetProps, WidgetState} from '@agnos-ui/react-headless/types';
import type {ToastApi} from '@agnos-ui/core-bootstrap/components/toast';
import {createToast as coreCreateToast} from '@agnos-ui/core-bootstrap/components/toast';

export * from '@agnos-ui/core-bootstrap/components/toast';

export type ToastWidget = AdaptWidgetSlots<import('@agnos-ui/core-bootstrap/components/toast').ToastWidget>;
export type ToastProps = WidgetProps<ToastWidget>;
export type ToastState = WidgetState<ToastWidget>;
export type ToastContext = AdaptSlotContentProps<import('@agnos-ui/core-bootstrap/components/toast').ToastContext>;
export const createToast: WidgetFactory<ToastWidget> = coreCreateToast as any;

const DefaultSlotStructure = (slotContext: ToastContext) => {
	const refCloseButton = useDirective(slotContext.widget.directives.closeButtonDirective);
	return (
		<>
			{slotContext.state.slotHeader && (
				<div className="toast-header">
					<Slot slotContent={slotContext.state.slotHeader} props={slotContext} />
					{slotContext.state.dismissible && <button className="btn-close me-0 ms-auto" {...refCloseButton} />}
				</div>
			)}

			<div className="toast-body">
				<Slot slotContent={slotContext.state.slotDefault} props={slotContext} />
			</div>
			{slotContext.state.dismissible && !slotContext.state.slotHeader && (
				<button className="btn-close btn-close-white me-2 m-auto" {...refCloseButton} />
			)}
		</>
	);
};

const defaultConfig: ToastProps = {
	slotStructure: DefaultSlotStructure,
};

export const Toast: ForwardRefExoticComponent<PropsWithChildren<ToastProps> & RefAttributes<ToastApi>> = forwardRef(function Toast(
	props: PropsWithChildren<ToastProps>,
	ref,
) {
	const [state, widget] = useWidgetWithConfig(createToast, props, 'toast', {...defaultConfig, slotDefault: props.children});
	const refToast = useDirectives([widget.directives.transitionDirective, widget.directives.autoHideDirective, widget.directives.bodyDirective]);
	useImperativeHandle(ref, () => widget.api, []);
	const slotContext = {
		state,
		widget,
	};

	return (
		<>
			{!state.hidden && (
				<div className={`toast ${state.dismissible ? 'toast-dismissible' : ''} ${!state.slotHeader ? 'd-flex' : ''}`} {...refToast}>
					<Slot slotContent={state.slotStructure} props={slotContext} />
				</div>
			)}
		</>
	);
});

// svelte/bootstrap/src/components/toast/Toast.svelte
<script lang="ts" context="module">
	import type {ToastProps as Props, ToastSlots as Slots} from './toast';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {createToast} from './toast';
	import {callWidgetFactory} from '../../config';
	import ToastDefaultStructure from './ToastDefaultStructure.svelte';

	const defaultConfig: Props = {
		slotStructure: ToastDefaultStructure,
	};
</script>

<script lang="ts">
	type $$Props = Props;
	type $$Slots = Slots;

	const widget = callWidgetFactory({
		factory: createToast,
		widgetName: 'toast',
		$$slots,
		$$props,
		defaultConfig,
		events: {
			onVisibleChange: (event) => {
				visible = event;
			},
		},
	});
	export let visible: boolean | undefined = undefined;
	export const api = widget.api;

	const {
		stores: {slotStructure$, hidden$},
		directives: {transitionDirective, autoHideDirective, bodyDirective},
		state$,
	} = widget;

	$: widget.patchChangedProps($$props);
	$: slotContext = {widget, state: $state$};
</script>

{#if !$hidden$}
	<div
		class="toast"
		class:toast-dismissible={$state$.dismissible}
		class:d-flex={!$state$.slotHeader}
		use:transitionDirective
		use:autoHideDirective
		use:bodyDirective
	>
		<Slot slotContent={$slotStructure$} props={slotContext} let:component let:props>
			<svelte:fragment slot="slot" let:props><slot name="structure" {...props} /></svelte:fragment>
			<svelte:component this={component} {...props}>
				<svelte:fragment let:state let:widget><slot {state} {widget} /></svelte:fragment>
				<svelte:fragment slot="header" let:state let:widget><slot name="header" {state} {widget} /></svelte:fragment>
				<svelte:fragment slot="structure" let:state let:widget><slot name="structure" {state} {widget} /></svelte:fragment>
			</svelte:component>
		</Slot>
	</div>
{/if}
