// svelte/demo/src/daisyui/samples/progressbar/Progressbar.svelte
<script lang="ts">
	import {createProgressbar, type ProgressbarProps} from '@agnos-ui/svelte-headless/components/progressbar';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	let {className, ...props}: Partial<Omit<ProgressbarProps, 'min'>> & {className?: string} = $props();

	const {
		state,
		directives: {ariaDirective},
	} = callWidgetFactory({
		factory: createProgressbar,
		widgetName: 'progressbar',
		get props() {
			return {...props};
		},
		enablePatchChanged: true,
	});
</script>

<progress use:ariaDirective class="progress {className}" value={state.value} max={state.max}></progress>

// angular/demo/daisyui/src/app/samples/progressbar/progressbar.component.ts
import {
	BaseWidgetDirective,
	auNumberAttribute,
	callWidgetFactory,
	type ProgressbarWidget,
	createProgressbar,
	UseDirective,
} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, input} from '@angular/core';

@Component({
	selector: 'app-progressbar',
	standalone: true,
	imports: [UseDirective],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `<progress
		class="progress"
		[class]="className()"
		[auUse]="directives.ariaDirective"
		[attr.value]="state.value()"
		[attr.max]="state.max()"
	></progress>`,
})
export class ProgressbarComponent extends BaseWidgetDirective<ProgressbarWidget> {
	readonly max = input(undefined, {transform: auNumberAttribute});
	readonly value = input(undefined, {transform: auNumberAttribute});
	readonly ariaLabel = input<string>();
	readonly className = input<string>();
	readonly ariaValueTextFn = input<(value: number, minimum: number, maximum: number) => string | undefined>();

	constructor() {
		super(
			callWidgetFactory({
				factory: createProgressbar,
				widgetName: 'progressbar',
			}),
		);
	}
}
