// react/lib/src/components/progressbar/progressbar.tsx
import {type PropsWithChildren} from 'react';
import type {ProgressbarContext, ProgressbarProps} from '@agnos-ui/react-headless/components/progressbar';
import {createProgressbar} from '@agnos-ui/react-headless/components/progressbar';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {toSlotContextWidget} from '@agnos-ui/react-headless/types';
import {Slot} from '@agnos-ui/react-headless/slot';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import classNames from 'classnames';

export * from '@agnos-ui/react-headless/components/progressbar';

function DefaultSlotContent(slotContext: ProgressbarContext) {
	const {striped, animated, className} = slotContext.state;
	const classes = classNames('progress-bar', {'progress-bar-striped': striped}, {'progress-bar-animated': animated}, className);
	return (
		<div className="progress" style={{height: slotContext.state.height}}>
			<div className={classes} style={{width: `${slotContext.state.percentage}%`}}>
				<Slot slotContent={slotContext.state.slotDefault} props={slotContext} />
			</div>
		</div>
	);
}

const defaultConfig: Partial<ProgressbarProps> = {
	slotStructure: DefaultSlotContent,
};

export const Progressbar = (props: PropsWithChildren<Partial<ProgressbarProps>>) => {
	const [state, widget] = useWidgetWithConfig(createProgressbar, props, 'progressbar', {...defaultConfig, slotDefault: props.children});
	const slotContext = {state, widget: toSlotContextWidget(widget)};
	const refAria = useDirective(widget.directives.ariaDirective);
	return (
		<div ref={refAria}>
			<Slot slotContent={state.slotStructure} props={slotContext} />
		</div>
	);
};

// svelte/bootstrap/src/components/progressbar/Progressbar.svelte
<script lang="ts">
	import {createProgressbar, type ProgressbarProps as Props, type ProgressbarSlots as Slots} from './progressbar';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {callWidgetFactory} from '../../config';
	import ProgressbarDefaultStructure from './ProgressbarDefaultStructure.svelte';

	type $$Props = Props;
	type $$Slots = Slots;

	const widget = callWidgetFactory({
		factory: createProgressbar,
		widgetName: 'progressbar',
		$$slots,
		$$props,
		defaultConfig: {
			slotStructure: ProgressbarDefaultStructure,
		},
		events: {},
	});
	const {
		stores: {slotStructure$, className$},
		state$,
		directives: {ariaDirective},
	} = widget;
	export const api = widget.api;

	$: widget.patchChangedProps($$props);
	$: slotContext = {widget, state: $state$};
</script>

<div use:ariaDirective class={$className$ || undefined}>
	<Slot slotContent={$slotStructure$} props={slotContext} let:component let:props>
		<svelte:fragment slot="slot" let:props><slot name="structure" {...props} /></svelte:fragment>
		<svelte:component this={component} {...props}>
			<svelte:fragment let:state let:widget><slot {state} {widget} /></svelte:fragment>
			<svelte:fragment slot="structure" let:state let:widget><slot name="structure" {state} {widget} /></svelte:fragment>
		</svelte:component>
	</Slot>
</div>
