// svelte/bootstrap/src/components/rating/Rating.svelte
<script lang="ts" context="module">
	import type {RatingProps as Props, RatingSlots as Slots} from './rating';
	import {createRating} from './rating';
	import {callWidgetFactory} from '../../config';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {createClassDirective, ssrAttributes} from '@agnos-ui/svelte-headless/utils/directive';
</script>

<script lang="ts">
	type $$Props = Props;
	type $$Slots = Slots;

	export let rating: number | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createRating,
		widgetName: 'rating',
		$$slots,
		$$props,
		events: {
			onRatingChange: (value: number) => {
				rating = value;
			},
		},
	});
	export const api = widget.api;

	const {
		stores: {visibleRating$, stars$, slotStar$},
		directives: {containerDirective, starDirective},
	} = widget;

	$: widget.patchChangedProps($$props);
</script>

<div use:containerDirective class="d-inline-flex" {...ssrAttributes(createClassDirective('d-inline-flex'), containerDirective)}>
	<!-- on:blur={onTouched} ?? -->
	{#each $stars$ as { fill, index }}
		<span class="visually-hidden">({index < $visibleRating$ ? '*' : ' '})</span>
		<span use:starDirective={{index}} {...ssrAttributes([starDirective, {index}])}>
			<Slot slotContent={$slotStar$} props={{fill, index}} let:component let:props>
				<svelte:fragment slot="slot" let:props><slot name="star" {...props} /></svelte:fragment>
				<svelte:component this={component} {...props} />
			</Slot>
		</span>
	{/each}
</div>

// react/bootstrap/src/components/rating/rating.tsx
import {Slot} from '@agnos-ui/react-headless/slot';
import {useWidgetWithConfig} from '../../config';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import React from 'react';
import {type RatingDirectives, type StarContext, createRating as coreCreateRating} from '@agnos-ui/core-bootstrap/components/rating';
import type {AdaptWidgetSlots, WidgetFactory, WidgetProps, WidgetState} from '@agnos-ui/react-headless/types';

export * from '@agnos-ui/react-headless/components/rating';

export type RatingWidget = AdaptWidgetSlots<import('@agnos-ui/core-bootstrap/components/rating').RatingWidget>;
export type RatingProps = WidgetProps<RatingWidget>;
export type RatingState = WidgetState<RatingWidget>;
export const createRating: WidgetFactory<RatingWidget> = coreCreateRating as any;

function Star({star, state, directive}: {star: StarContext; state: RatingState; directive: RatingDirectives['starDirective']}) {
	const arg = {index: star.index};
	return (
		<React.Fragment key={star.index}>
			<span className="visually-hidden">({star.index < state.visibleRating ? '*' : ' '})</span>
			<span {...useDirective(directive, arg)}>
				<Slot slotContent={state.slotStar} props={star}></Slot>
			</span>
		</React.Fragment>
	);
}

export function Rating(props: RatingProps) {
	const [state, widget] = useWidgetWithConfig(createRating, props, 'rating');

	const {
		directives: {containerDirective, starDirective},
	} = widget;

	return (
		<div className="d-inline-flex" {...useDirective(containerDirective)}>
			{state.stars.map((star) => (
				<Star key={star.index} star={star} state={state} directive={starDirective} />
			))}
		</div>
	);
}
