// svelte/bootstrap/src/components/select/Select.svelte
<script lang="ts" context="module">
	import type {SelectProps as Props, SelectWidget, SelectSlots as Slots} from './select';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {createSelect} from './select';
	import {callWidgetFactory} from '../../config';
</script>

<script lang="ts">
	type Item = $$Generic; // eslint-disable-line no-undef
	type $$Props = Props<Item>;
	type $$Slots = Slots<Item>;

	export let open: boolean | undefined = false;
	export let filterText: string | undefined = undefined;
	export let selected: Item[] | undefined = undefined;

	const widget = callWidgetFactory<SelectWidget<Item>>({
		factory: createSelect,
		widgetName: 'select',
		$$slots,
		$$props,
		events: {
			onOpenChange: function (isOpen: boolean): void {
				open = isOpen;
			},
			onSelectedChange: (newSelection) => {
				selected = newSelection;
			},
			onFilterTextChange: (value) => {
				filterText = value;
			},
		},
	});
	export const api = widget.api;
	const {
		stores: {
			id$,
			ariaLabel$,
			badgeClassName$,
			className$,
			filterText$,
			highlighted$,
			menuClassName$,
			menuItemClassName$,
			open$,
			placement$,
			selectedContexts$,
			slotBadgeLabel$,
			slotItem$,
			visibleItems$,
		},
		state$,
		actions: {onInput, onInputKeydown, onBadgeKeydown},
		directives: {floatingDirective, hasFocusDirective, referenceDirective, inputContainerDirective},
	} = widget;

	$: widget.patchChangedProps($$props);
	$: menuId = `${$id$}-menu`;
</script>

<div use:referenceDirective class="au-select dropdown border border-1 p-1 mb-3 d-block {$className$}">
	<div
		use:hasFocusDirective
		use:inputContainerDirective
		role="combobox"
		class="d-flex align-items-center flex-wrap"
		aria-controls={menuId}
		aria-haspopup="listbox"
		aria-expanded={$open$}
	>
		{#each $selectedContexts$ as itemContext (itemContext.id)}
			<!-- svelte-ignore a11y-no-static-element-interactions -->
			<div tabindex="-1" class={`au-select-badge me-1 ${$badgeClassName$}`} on:keydown={(e) => onBadgeKeydown(e, itemContext.item)}>
				<Slot slotContent={$slotBadgeLabel$} props={{state: $state$, widget, itemContext}} let:component let:props>
					<svelte:fragment slot="slot" let:props><slot name="badgeLabel" {...props} /></svelte:fragment>
					<svelte:component this={component} {...props}>
						<svelte:fragment slot="badgeLabel" let:itemContext let:state let:widget
							><slot name="badgeLabel" {itemContext} {state} {widget} /></svelte:fragment
						>
						<svelte:fragment slot="item" let:itemContext let:state let:widget><slot name="item" {itemContext} {state} {widget} /></svelte:fragment>
					</svelte:component>
				</Slot>
			</div>
		{/each}
		<input
			id={$id$}
			aria-label={$ariaLabel$}
			type="text"
			class="au-select-input flex-grow-1 border-0"
			value={$filterText$}
			aria-autocomplete="list"
			autoCorrect="off"
			autoCapitalize="none"
			autoComplete="off"
			on:input={onInput}
			on:keydown={onInputKeydown}
		/>
	</div>
	{#if $open$ && $visibleItems$.length > 0}
		<ul
			role="listbox"
			id={menuId}
			use:hasFocusDirective
			use:floatingDirective
			class="dropdown-menu show {$menuClassName$}"
			data-popper-placement={$placement$}
			on:mousedown|preventDefault
		>
			{#each $visibleItems$ as itemContext (itemContext.id)}
				{@const isHighlighted = itemContext === $highlighted$}
				{@const isSelected = itemContext.selected}
				<!-- svelte-ignore a11y-click-events-have-key-events -->
				<li
					role="option"
					aria-selected={isSelected}
					class={`au-select-item dropdown-item position-relative ${$menuItemClassName$}`}
					class:text-bg-primary={isHighlighted}
					class:selected={isSelected}
					on:click={() => widget.api.toggleItem(itemContext.item)}
					style:cursor="pointer"
				>
					<Slot slotContent={$slotItem$} props={{state: $state$, widget, itemContext}} let:component let:props>
						<svelte:fragment slot="slot" let:props><slot name="item" {...props} /></svelte:fragment>
						<svelte:component this={component} {...props}>
							<svelte:fragment slot="badgeLabel" let:itemContext let:state let:widget
								><slot name="badgeLabel" {itemContext} {state} {widget} /></svelte:fragment
							>
							<svelte:fragment slot="item" let:itemContext let:state let:widget><slot name="item" {itemContext} {state} {widget} /></svelte:fragment>
						</svelte:component>
					</Slot>
				</li>
			{/each}
		</ul>
	{/if}
</div>

// react/bootstrap/src/components/select/select.tsx
import {useWidgetWithConfig} from '../../config';
import {Slot} from '@agnos-ui/react-headless/slot';
import type {AdaptSlotContentProps, AdaptWidgetSlots, PropsConfig, WidgetProps, WidgetState} from '@agnos-ui/react-headless/types';
import {toSlotContextWidget} from '@agnos-ui/react-headless/types';
import {useDirective, useDirectives} from '@agnos-ui/react-headless/utils/directive';
import type {SyntheticEvent} from 'react';
import type {ItemContext} from '@agnos-ui/core-bootstrap/components/select';
import {createSelect as coreCreateSelect} from '@agnos-ui/core-bootstrap/components/select';

export * from '@agnos-ui/core-bootstrap/components/select';

export type SelectWidget<Item> = AdaptWidgetSlots<import('@agnos-ui/core-bootstrap/components/select').SelectWidget<Item>>;
export type SelectProps<Item> = WidgetProps<SelectWidget<Item>>;
export type SelectState<Item> = WidgetState<SelectWidget<Item>>;
export type SelectContext<Item> = AdaptSlotContentProps<import('@agnos-ui/core-bootstrap/components/select').SelectContext<Item>>;
export type SelectItemContext<Item> = AdaptSlotContentProps<import('@agnos-ui/core-bootstrap/components/select').SelectItemContext<Item>>;
export const createSelect: <Item>(propsConfig?: PropsConfig<SelectProps<Item>>) => SelectWidget<Item> = coreCreateSelect as any;

function preventDefault(e: SyntheticEvent) {
	e.preventDefault();
}

function DefaultBadge<Item>(slotContext: SelectItemContext<Item>) {
	return <>{'' + slotContext.itemContext.item}</>;
}

function DefaultItem<Item>(slotContext: SelectItemContext<Item>) {
	return <>{'' + slotContext.itemContext.item}</>;
}

function BadgeContainer<Item>({itemContext, slotContext}: {itemContext: ItemContext<Item>; slotContext: SelectContext<Item>}) {
	const state = slotContext.state;
	return (
		<div
			key={itemContext.id}
			tabIndex={-1}
			className={`au-select-badge me-1 ${state.badgeClassName}`}
			onKeyDown={(e) => slotContext.widget.actions.onBadgeKeydown(e.nativeEvent, itemContext.item)}
		>
			<Slot slotContent={state.slotBadgeLabel} props={{...slotContext, itemContext}}></Slot>
		</div>
	);
}

function Badges<Item>({slotContext}: {slotContext: SelectContext<Item>}) {
	const badges = [];
	for (const itemContext of slotContext.state.selectedContexts) {
		badges.push(<BadgeContainer key={itemContext.id} itemContext={itemContext} slotContext={slotContext} />);
	}

	return badges.length ? <>{badges}</> : null;
}

function Rows<Item>({slotContext}: {slotContext: SelectContext<Item>}) {
	const {widget, state} = slotContext;
	const highlighted = state.highlighted;
	return (
		<>
			{state.visibleItems.map((itemContext) => {
				const {id} = itemContext;
				const classname = ['au-select-item dropdown-item position-relative'];
				if (itemContext === highlighted) {
					classname.push('text-bg-primary');
				}
				if (itemContext.selected) {
					classname.push('selected');
				}
				return (
					<li
						key={id}
						role="option"
						aria-selected={itemContext.selected}
						className={classname.join(' ')}
						onClick={() => widget.api.toggleItem(itemContext.item)}
						style={{cursor: 'pointer'}}
					>
						<Slot slotContent={state.slotItem} props={{...slotContext, itemContext}}></Slot>
					</li>
				);
			})}
		</>
	);
}

const defaultConfig: SelectProps<any> = {
	slotBadgeLabel: DefaultBadge,
	slotItem: DefaultItem,
};

export function Select<Item>(props: SelectProps<Item>) {
	const [state, widget] = useWidgetWithConfig<SelectWidget<Item>>(createSelect, props, 'select', defaultConfig);
	const slotContext: SelectContext<Item> = {state, widget: toSlotContextWidget(widget)};
	const {id, ariaLabel, visibleItems, filterText, open, className, menuClassName, placement} = state;
	const menuId = `${id}-menu`;

	const {
		directives: {floatingDirective, hasFocusDirective, referenceDirective, inputContainerDirective},
	} = widget;
	const refSetMenu = useDirectives([hasFocusDirective, floatingDirective]);
	return (
		<div className={`au-select dropdown border border-1 p-1 mb-3 d-block ${className}`} {...useDirective(referenceDirective)}>
			<div
				{...useDirectives([hasFocusDirective, inputContainerDirective])}
				role="combobox"
				className="d-flex align-items-center flex-wrap"
				aria-controls={menuId}
				aria-haspopup="listbox"
				aria-expanded={open}
			>
				<Badges slotContext={slotContext}></Badges>
				<input
					id={id}
					aria-label={ariaLabel}
					className="au-select-input flex-grow-1 border-0"
					type="text"
					value={filterText}
					aria-autocomplete="list"
					autoCorrect="off"
					autoCapitalize="none"
					autoComplete="off"
					onInput={widget.actions.onInput}
					onKeyDown={(e) => widget.actions.onInputKeydown(e.nativeEvent)}
				/>
			</div>
			{open && visibleItems.length > 0 && (
				<ul
					{...refSetMenu}
					role="listbox"
					id={menuId}
					className={`dropdown-menu show ${menuClassName}`}
					data-popper-placement={placement}
					onMouseDown={preventDefault}
				>
					<Rows slotContext={slotContext}></Rows>
				</ul>
			)}
		</div>
	);
}
